import { INodeType, INodeTypeDescription } from 'n8n-workflow';

export class Notsy implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Notsy Facturación',
		name: 'notsy',
		icon: 'file:notsy.svg',
		group: ['transform'],
		version: 1,
		subtitle: '={{$parameter["operation"]}}',
		description: 'Issue Mexican CFDI 4.0 invoices, manage customers and read tax reports',
		defaults: { name: 'Notsy' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'notsyApi', required: true }],
		requestDefaults: {
			baseURL: 'https://facturacion-api.notsy.com.mx',
			headers: { 'Content-Type': 'application/json' },
		},
		properties: [
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				options: [
					{
						name: 'Cancel CFDI',
						value: 'cancelar',
						action: 'Cancel an issued invoice',
						description: 'Cancel an issued CFDI with the SAT (reasons 01-04)',
						routing: {
							request: {
								method: 'POST',
								url: '=/agent/facturas/{{$parameter["factura_id"]}}/cancelar',
							},
						},
					},
					{
						name: 'Create Customer',
						value: 'createCliente',
						action: 'Create or update a customer',
						description: 'Create or update a customer and get a reusable customer ID',
						routing: { request: { method: 'POST', url: '/agent/clientes' } },
					},
					{
						name: 'Find Customers',
						value: 'listClientes',
						action: 'Find saved customers',
						description: 'List or search your saved customers by name or RFC',
						routing: { request: { method: 'GET', url: '/agent/clientes' } },
					},
					{
						name: 'Find Invoices',
						value: 'listFacturas',
						action: 'Find recent invoices',
						description: 'List your most recent invoices',
						routing: { request: { method: 'GET', url: '/agent/facturas' } },
					},
					{
						name: 'Get Income Tax Report',
						value: 'reporteIsr',
						action: 'Get the income tax report for legal entities',
						description: 'Provisional ISR payment for Mexican legal entities (personas morales)',
						routing: { request: { method: 'GET', url: '/agent/reportes/isr' } },
					},
					{
						name: 'Get Invoice Status',
						value: 'getFactura',
						action: 'Get the status of an invoice',
						description: 'Get the status and details of one invoice',
						routing: {
							request: {
								method: 'GET',
								url: '=/agent/facturas/{{$parameter["factura_id"]}}',
							},
						},
					},
					{
						name: 'Get VAT Report',
						value: 'reporteIva',
						action: 'Get the value added tax report for a period',
						description: 'Cash-flow VAT (IVA) report: charged, creditable and due',
						routing: { request: { method: 'GET', url: '/agent/reportes/iva' } },
					},
					{
						name: 'Issue CFDI',
						value: 'emitir',
						action: 'Issue and stamp a tax invoice',
						description: 'Stamp an official CFDI 4.0 with the Mexican tax authority (SAT)',
						routing: { request: { method: 'POST', url: '/agent/facturas' } },
					},
					{
						name: 'My Account',
						value: 'whoami',
						action: 'View the API key permissions limits and usage',
						description: 'Return the permissions, limits and usage of the API key',
						routing: { request: { method: 'GET', url: '/agent/whoami' } },
					},
					{
						name: 'Preview Invoice',
						value: 'preview',
						action: 'Preview an invoice without stamping it',
						description: 'Validate and calculate totals at no cost, before issuing',
						routing: { request: { method: 'POST', url: '/agent/facturas/preview' } },
					},
					{
						name: 'Resolve SAT Keys',
						value: 'resolver',
						action: 'Resolve SAT catalog keys from a description',
						description: 'Turn a description into clave_prodserv, clave_unidad and more',
						routing: { request: { method: 'POST', url: '/agent/resolver-claves-sat' } },
					},
				],
				default: 'resolver',
			},

			// ── Resolve SAT Keys ──
			{
				displayName: 'Description',
				name: 'descripcion',
				type: 'string',
				default: '',
				required: true,
				placeholder: 'marketing consulting',
				description: 'What you sell, in natural language',
				displayOptions: { show: { operation: ['resolver'] } },
				routing: { send: { type: 'body', property: 'descripcion' } },
			},
			{
				displayName: 'Apply VAT',
				name: 'con_iva',
				type: 'boolean',
				default: true,
				description: 'Whether the item is subject to VAT (IVA)',
				displayOptions: { show: { operation: ['resolver'] } },
				routing: { send: { type: 'body', property: 'con_iva' } },
			},

			// ── Preview / Issue ──
			{
				displayName: 'Line Items (JSON)',
				name: 'conceptos',
				type: 'json',
				default: '[\n  {\n    "descripcion": "Consultoria",\n    "clave_prodserv": "80101500",\n    "clave_unidad": "E48",\n    "cantidad": 1,\n    "valor_unitario": 1000,\n    "precio_incluye_iva": false\n  }\n]',
				required: true,
				description: 'List of CFDI line items (conceptos)',
				displayOptions: { show: { operation: ['preview', 'emitir'] } },
				routing: { send: { type: 'body', property: 'conceptos' } },
			},
			{
				displayName: 'Customer (JSON)',
				name: 'cliente',
				type: 'json',
				default: '{\n  "rfc": "",\n  "nombre": "",\n  "regimen_fiscal": "",\n  "cp": "",\n  "uso_cfdi": "G03"\n}',
				description: 'CFDI recipient, or pass cliente_id of a saved customer',
				displayOptions: { show: { operation: ['preview', 'emitir'] } },
				routing: { send: { type: 'body', property: 'cliente' } },
			},
			{
				displayName: 'Payment Method',
				name: 'metodo_pago',
				type: 'options',
				options: [
					{ name: 'PUE - Paid in a Single Payment', value: 'PUE' },
					{ name: 'PPD - Paid in Installments (Credit)', value: 'PPD' },
				],
				default: 'PUE',
				description: 'SAT payment method (metodo de pago)',
				displayOptions: { show: { operation: ['preview', 'emitir'] } },
				routing: { send: { type: 'body', property: 'metodo_pago' } },
			},
			{
				displayName: 'Payment Form (SAT Code)',
				name: 'forma_pago',
				type: 'string',
				default: '03',
				description: 'SAT payment form code: 03 transfer, 01 cash, 04 credit card, etc',
				displayOptions: { show: { operation: ['preview', 'emitir'] } },
				routing: { send: { type: 'body', property: 'forma_pago' } },
			},

			// ── Cancel / Get Invoice (path param) ──
			{
				displayName: 'Invoice ID',
				name: 'factura_id',
				type: 'string',
				default: '',
				required: true,
				description: 'Internal invoice ID, from Issue CFDI or Find Invoices',
				displayOptions: { show: { operation: ['cancelar', 'getFactura'] } },
			},
			{
				displayName: 'Cancellation Reason',
				name: 'motivo',
				type: 'options',
				options: [
					{ name: '01 - Issued With Errors, With Replacement', value: '01' },
					{ name: '02 - Issued With Errors, No Replacement', value: '02' },
					{ name: '03 - The Operation Did Not Take Place', value: '03' },
					{ name: '04 - Nominative Transaction in a Global Invoice', value: '04' },
				],
				default: '02',
				description: 'SAT cancellation reason code',
				displayOptions: { show: { operation: ['cancelar'] } },
				routing: { send: { type: 'body', property: 'motivo' } },
			},
			{
				displayName: 'Replacement CFDI UUID',
				name: 'uuid_sustituye',
				type: 'string',
				default: '',
				description: 'Required only when reason is 01: the UUID of the CFDI that replaces this one',
				displayOptions: { show: { operation: ['cancelar'] } },
				routing: { send: { type: 'body', property: 'uuid_sustituye' } },
			},

			// ── Find Customers / Find Invoices (query) ──
			{
				displayName: 'Search',
				name: 'q',
				type: 'string',
				default: '',
				description: 'Filter customers by name or RFC. Leave empty to list the most used.',
				displayOptions: { show: { operation: ['listClientes'] } },
				routing: { send: { type: 'query', property: 'q' } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
				displayOptions: { show: { operation: ['listClientes', 'listFacturas'] } },
				routing: { send: { type: 'query', property: 'limit' } },
			},

			// ── Create Customer (body) ──
			{
				displayName: 'RFC',
				name: 'rfc',
				type: 'string',
				default: '',
				required: true,
				description: 'Customer tax ID (RFC)',
				displayOptions: { show: { operation: ['createCliente'] } },
				routing: { send: { type: 'body', property: 'rfc' } },
			},
			{
				displayName: 'Legal Name',
				name: 'nombre',
				type: 'string',
				default: '',
				required: true,
				description: 'Exact legal name as registered with the SAT',
				displayOptions: { show: { operation: ['createCliente'] } },
				routing: { send: { type: 'body', property: 'nombre' } },
			},
			{
				displayName: 'Tax Regime (SAT Code)',
				name: 'regimen_fiscal',
				type: 'string',
				default: '',
				required: true,
				description: 'SAT tax regime code, e.g. 601, 612, 616',
				displayOptions: { show: { operation: ['createCliente'] } },
				routing: { send: { type: 'body', property: 'regimen_fiscal' } },
			},
			{
				displayName: 'ZIP Code',
				name: 'cp',
				type: 'string',
				default: '',
				required: true,
				description: 'Customer postal code (codigo postal)',
				displayOptions: { show: { operation: ['createCliente'] } },
				routing: { send: { type: 'body', property: 'cp' } },
			},
			{
				displayName: 'CFDI Use (Default)',
				name: 'uso_cfdi',
				type: 'string',
				default: 'G03',
				description: 'Default uso_cfdi for this customer, e.g. G03, S01',
				displayOptions: { show: { operation: ['createCliente'] } },
				routing: { send: { type: 'body', property: 'uso_cfdi' } },
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				description: 'Customer email',
				displayOptions: { show: { operation: ['createCliente'] } },
				routing: { send: { type: 'body', property: 'email' } },
			},

			// ── VAT Report (query) ──
			{
				displayName: 'Month (YYYY-MM)',
				name: 'mes',
				type: 'string',
				default: '',
				placeholder: '2026-05',
				description: 'Period in YYYY-MM format. Leave empty for all downloaded data.',
				displayOptions: { show: { operation: ['reporteIva'] } },
				routing: { send: { type: 'query', property: 'mes' } },
			},

			// ── Income Tax Report (query) ──
			{
				displayName: 'Year',
				name: 'anio',
				type: 'number',
				default: 2026,
				required: true,
				description: 'Fiscal year',
				displayOptions: { show: { operation: ['reporteIsr'] } },
				routing: { send: { type: 'query', property: 'anio' } },
			},
			{
				displayName: 'Month',
				name: 'isrMes',
				type: 'number',
				typeOptions: { minValue: 1, maxValue: 12 },
				default: 1,
				required: true,
				description: 'Month number from 1 to 12',
				displayOptions: { show: { operation: ['reporteIsr'] } },
				routing: { send: { type: 'query', property: 'mes' } },
			},
			{
				displayName: 'Profit Coefficient',
				name: 'coeficiente',
				type: 'number',
				default: 0,
				required: true,
				description: 'Coeficiente de utilidad from last year (taxable profit divided by nominal income)',
				displayOptions: { show: { operation: ['reporteIsr'] } },
				routing: { send: { type: 'query', property: 'coeficiente' } },
			},
			{
				displayName: 'Pending Tax Losses',
				name: 'perdidas',
				type: 'number',
				default: 0,
				description: 'Optional prior tax losses to apply',
				displayOptions: { show: { operation: ['reporteIsr'] } },
				routing: { send: { type: 'query', property: 'perdidas' } },
			},
			{
				displayName: 'PTU Paid',
				name: 'ptu',
				type: 'number',
				default: 0,
				description: 'Optional PTU paid this fiscal year',
				displayOptions: { show: { operation: ['reporteIsr'] } },
				routing: { send: { type: 'query', property: 'ptu' } },
			},
			{
				displayName: 'Prior Provisional Payments',
				name: 'pagos_previos',
				type: 'number',
				default: 0,
				description: 'Optional ISR provisional payments already made this year',
				displayOptions: { show: { operation: ['reporteIsr'] } },
				routing: { send: { type: 'query', property: 'pagos_provisionales_previos' } },
			},
		],
	};
}
